# Generated by Django 4.1 on 2022-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(verbose_name="Number")),
            ],
        ),
        migrations.AlterField(
            model_name="size",
            name="title",
            field=models.CharField(
                choices=[("Small", "Small"), ("Medium", "Medium"), ("Large", "Large")],
                max_length=10,
                verbose_name="Size",
            ),
        ),
    ]
