# Generated by Django 4.1 on 2022-09-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0003_alter_quant_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quant",
            name="number",
            field=models.CharField(
                choices=[("2", 2), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                max_length=2,
                verbose_name="Number",
            ),
        ),
    ]
