# Generated by Django 4.1 on 2022-09-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0005_alter_quant_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Quant",
        ),
    ]
