# Generated by Django 4.1 on 2022-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0006_delete_quant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="topping1",
            field=models.CharField(max_length=100, verbose_name="Topping_1"),
        ),
        migrations.AlterField(
            model_name="pizza",
            name="topping2",
            field=models.CharField(max_length=100, verbose_name="Topping_2"),
        ),
        migrations.AlterField(
            model_name="size",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Size"),
        ),
    ]
